version: '3.1'

services: 
  
  postgres:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d